### ISSUE TITLE
problem loading in ipython windows 10 and Ubuntu 20.04

### ISSUE THREAD

**Issue by lazypolyling** [stephantul/reach#15]
Hi stephan, thanks for making this package!

I've been having trouble importing it on windows 10 and Ubuntu 20.04 in jupyter notebooks: `from reach import Reach` gives an import error (`import reach` works, but using `rech.Reach.load()` doesn't work): unknown location yet the package is visible in the site packages on both machines, under the correct name:
- I `git cloned` this package into my Anaconda site-packages on both windows 10 and ubuntu
- I checked the python versions in ipython and powershell, they're the same in both windows 10 and ubuntu
- I also checked the PATH variable in both, also the same result in both windows 10 and ubuntu 
- I restarted the PCs but it made no difference

I don't think this issue is related to the package versions on my machines (which probably also don't match the package requirements) because the python interpreter doesn't know where to find `Reach`. 

Do you know of any way I could fix this locally? 
Thanks anyways!

Best,
Lisa

edit: I can't import it via the python interpreter in the command line either.

**Comment by stephantul** [comment]
Hi Lisa,

thanks for using Reach. Did you try `pip install`? AFAIK, `git clone`ing your packages into site-packages is not the correct way to install a package. Instead, you should clone it somewhere and then run `python setup.py install`. This will move it into the `site-packages` directory associated with your python interpreter.

**Comment by lazypolyling** [comment]
Hi Stephan,

I did not realize it was on pypi, thanks so much for the quick response! I'm so happy, it works!! 
Up until now I've used git clone into site packages multiple times for my own projects, but it seems not to be the most reliable way indeed. 
Thanks again for making the package! Will be using it a lot the coming week so I'll post issues, if I come across any :) 

All the best!
