### ISSUE TITLE
OOV

### ISSUE THREAD

**Issue by Bachstelze** [stephantul/reach#6]
What is meant with "[The] approaches know how to deal with OOV words" ?
Is the deal to delete them?

**Comment by Bachstelze** [comment]
Yes thanks, the question is clear. But I would appreciate a hook in the relevant code, so that it is easy to implement a costume replacement with for example synonyms of the oov word which are in the vocabulary.

**Comment by stephantul** [comment]
Wouldn't it be easier to do this before passing things to reach? You know beforehand which words are and aren't OOV, so it is probably easier to replace them with other words/stems before you pass them to reach. This is also the approach I would take in my own work.

In any case, if you think this would be a useful addition you can always submit a PR.
