### ISSUE TITLE
Missing dependency: TQDM

### ISSUE THREAD

**Issue by vriesdemichael** [stephantul/reach#7]
This basic usage yields an error:

```python

from reach import Reach

r = Reach.load("path/to/vector")
```
I think this package needs to add tqdm as dependency, or truly make it optional by importing it optionally.

**Comment by stephantul** [comment]
Hey, so you mean that I should add it to `install_requires` in `setup.py`? Because it is a dependency in `requirements.txt`.

**Comment by vriesdemichael** [comment]
Yes, at the moment you have a `requirements.txt` (which is not used by default when installing from pypi).

I suggest you merge all your dependencies in `install_requires`, that way you can use reach out of the box when installing from pypi.

I'd also just like to say that I really do enjoy the simplicity of your module!

**Comment by stephantul** [comment]
Alright, I'll get to it. Thanks for the comment!

**Comment by stephantul** [comment]
It's updated now on pip as well as here (version `3.2.1`). Let me know if it works.
